#include "FEC_channel_decode_test_imp.h"

#include <iostream>

FEC_CHANNEL_DECODE::FEC_CHANNEL_DECODE_TEST_IMP::FEC_CHANNEL_DECODE_TEST_IMP(){
    
}

FEC_CHANNEL_DECODE::FEC_CHANNEL_DECODE_TEST_IMP::~FEC_CHANNEL_DECODE_TEST_IMP(){
    
}

void FEC_CHANNEL_DECODE::FEC_CHANNEL_DECODE_TEST_IMP::init(){

}
        
void FEC_CHANNEL_DECODE::FEC_CHANNEL_DECODE_TEST_IMP::encode(){

}
        
void FEC_CHANNEL_DECODE::FEC_CHANNEL_DECODE_TEST_IMP::decode(){}
